services:
  db:
    image: postgres:16
    container_name: finance_pg
    environment:
      POSTGRES_DB: finance
      POSTGRES_USER: finance_user
      POSTGRES_PASSWORD: finance_pass
    ports:
      - "5432:5432"
    volumes:
      - finance_pg_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d

volumes:
  finance_pg_data: